### ISSUE TITLE
Repository description

### ISSUE THREAD

**Issue by navoznov** [savisitor15/TimeTools#1]
Write the reposiroty description with info about the mod installation.

**Comment by savisitor15** [comment]
Hello @navoznov,
Installation is pretty simple, you can either goto: https://mods.factorio.com/mod/TimeTools
and simply download the zip file.
Or create the zip yourself.
the zip should be called: TimeTools_[version] in this case 1.0.36
and contain a folder by the same name:

example: TimeTools_1.0.36.zip -> TimeTools_1.0.36  -> All the files from the repo.

When I have some free time I may write a script that builds this for linux systems at some point.
